/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_24 (
    input [11:0] a,
    input [11:0] b,
    input [1:0] alufn,
    output reg [191:0] s,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [11:0] xs;
  
  always @* begin
    s = $signed(12'h000);
    z = 1'h0;
    v = 1'h0;
    n = 1'h0;
    
    case (alufn)
      2'h0: begin
        s = $signed(a) + $signed(b);
        xs = $signed(a) + $signed(b);
        z = ~((|xs));
        v = (a[11+0-:1] && b[11+0-:1] && ~(xs[11+0-:1])) || (~(a[11+0-:1]) && ~(b[11+0-:1]) && xs[11+0-:1]);
        n = xs[11+0-:1];
      end
      2'h1: begin
        s = $signed(a) - $signed(b);
        xs = $signed(a) - $signed(b);
        z = ~((|xs));
        v = (a[11+0-:1] && b[11+0-:1] && ~(xs[11+0-:1])) || (~(a[11+0-:1]) && ~(b[11+0-:1]) && xs[11+0-:1]);
        n = xs[11+0-:1];
      end
      2'h2: begin
        s = $signed(a) * $signed(b);
        xs = $signed(a) * $signed(b);
        z = ~((|xs));
        v = (a[11+0-:1] && b[11+0-:1] && ~(xs[11+0-:1])) || (~(a[11+0-:1]) && ~(b[11+0-:1]) && xs[11+0-:1]);
        n = xs[11+0-:1];
      end
    endcase
  end
endmodule
