/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module colour_mux4_15 (
    input [1:0] button,
    output reg [11:0] out
  );
  
  
  
  always @* begin
    out = 12'h000;
    
    case (button)
      2'h0: begin
        out = 12'h000;
      end
      2'h1: begin
        out = 12'h001;
      end
      2'h2: begin
        out = 12'h002;
      end
      2'h3: begin
        out = 12'h003;
      end
    endcase
  end
endmodule
