/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_27 (
    input [11:0] a,
    input [11:0] b,
    input [1:0] alufn,
    output reg [11:0] cmp
  );
  
  
  
  wire [192-1:0] M_adder_s;
  wire [1-1:0] M_adder_z;
  wire [1-1:0] M_adder_v;
  wire [1-1:0] M_adder_n;
  reg [12-1:0] M_adder_a;
  reg [12-1:0] M_adder_b;
  reg [2-1:0] M_adder_alufn;
  adder_24 adder (
    .a(M_adder_a),
    .b(M_adder_b),
    .alufn(M_adder_alufn),
    .s(M_adder_s),
    .z(M_adder_z),
    .v(M_adder_v),
    .n(M_adder_n)
  );
  
  always @* begin
    cmp = 12'h000;
    M_adder_a = $signed(a);
    M_adder_b = $signed(b);
    M_adder_alufn[0+1-:2] = 2'h1;
    
    case (alufn)
      2'h1: begin
        cmp[0+0-:1] = M_adder_z;
      end
      2'h2: begin
        cmp[0+0-:1] = M_adder_n ^ M_adder_v;
      end
      2'h3: begin
        cmp[0+0-:1] = (M_adder_n ^ M_adder_v) | M_adder_z;
      end
    endcase
  end
endmodule
