/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     HEIGHT = 8
     WIDTH = 192
*/
module register_13 (
    input clk,
    input rst,
    input wr,
    input [1535:0] data,
    output reg [1535:0] out
  );
  
  localparam HEIGHT = 4'h8;
  localparam WIDTH = 8'hc0;
  
  
  reg [1535:0] M_reg_d, M_reg_q = 1'h0;
  
  always @* begin
    M_reg_d = M_reg_q;
    
    if (wr == 1'h1) begin
      M_reg_d = data;
    end else begin
      M_reg_d = M_reg_q;
    end
    out = M_reg_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_reg_q <= 1'h0;
    end else begin
      M_reg_q <= M_reg_d;
    end
  end
  
endmodule
