/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_26 (
    input [11:0] a,
    input [11:0] b,
    input [1:0] alufn,
    output reg [11:0] shift
  );
  
  
  
  always @* begin
    shift = 12'h000;
    
    case (alufn)
      2'h0: begin
        shift = $signed(a) << b[0+2-:3];
      end
      2'h1: begin
        shift = $signed(a) >> b[0+2-:3];
      end
      2'h2: begin
        shift = $signed(a) <<< b[0+2-:3];
      end
      2'h3: begin
        shift = $signed(a) >>> b[0+2-:3];
      end
    endcase
  end
endmodule
